[vc_row el_class="margin-bottom"]
	[vc_column offset="vc_col-md-6"]
		[title size="small" position="left" decoration="off" underline="off" style="dark" text="CONTACT DETAILS" subtitle="Would like to talk?"]
		[vc_column_text]If you have a story to share or a question that has not been answered on our website, please get in touch with us via contact details listed below or fill in the form on the right.[/vc_column_text]
		[contact_info address="777 Franklin St, San Francisco" phone="+1 420-240-6000" email="contact@adventuretours.com" skype="adventure.tours"]
		[social_icons title="" facebook_url="http://facebook.com" twitter_url="http://twitter.com" googleplus_url="http://googleplus.com" pinterest_url="http://pinterest.com" linkedin_url="http://linkedin.com"]
	[/vc_column]
	[vc_column offset="vc_col-md-6"]
		[title size="small" position="left" decoration="off" underline="off" style="dark" text="GET IN TOUCH" subtitle="Have a question?"]
		[contact-form-7 id="86"]
	[/vc_column]
[/vc_row]
[vc_row]
	[vc_column]
		[google_map coordinates="37.7919688,-122.4243583" zoom="10" height="400" width_mode="full-width" css_class="stick-to-bottom"]
	[/vc_column]
[/vc_row]