[vc_row]
	[vc_column offset="vc_col-md-9"]
		[title size="big" position="left" decoration="off" underline="off" style="dark" text="WHY CHOOSE US?"]
		[icons_set row_size="3"]
			[icon_item icon="td-earth-1" title="Diverse Destinations"]Habitasse. Nunc mollis erat dapibus in commodo eu nisi. Odio purus magnis lorem.[/icon_item]
			[icon_item icon="td-banknote-1" title="Value for Money"]Nulla imperdiet dictum laoreet netus. Habitant ullamcorper. Auctor auctor cras.[/icon_item]
			[icon_item icon="td-photocamera-5" title="Beautiful Places"]Eu molestie Purus ac. Facilisis hac in metus nunc parturient ornare consequat enim.[/icon_item]
			[icon_item icon="td-calendar-2" title="Fast Booking"]Torquent egestas. Per integer placerat ipsum quam adipiscing vehicula nisi.[/icon_item]
			[icon_item icon="td-chat" title="Support Team"]Turpis accumsan. Proin id ligula suspendisse. Aliquet fringilla, aptent eu dignissim.[/icon_item]
			[icon_item icon="td-heart" title="Passionate Travel"]Metus cubilia aenean. Fusce, dapibus netus nullam interdum ut vehicula.[/icon_item]
		[/icons_set]
	[/vc_column]
	[vc_column offset="vc_col-md-3"]
		[vc_raw_html]JTNDZGl2JTIwY2xhc3MlM0QlMjJtYXJnaW4tdG9wJTIwbWFyZ2luLWJvdHRvbSUyMHZpc2libGUtc20lMjB2aXNpYmxlLXhzJTIyJTNFJTNDJTJGZGl2JTNF[/vc_raw_html]
		[tour_search_form hide_text_field="off" title="Search Tours" note="Find your dream tour today!"]
	[/vc_column]
[/vc_row]
[vc_row]
	[vc_column]
		[tour_carousel title_underline="off" description_words_limit="20" slides_number="3" arrow_style="light" order="DESC" orderby="date" title="MOST POPULAR TOURS" sub_title="Take a Look at Our" css_class="margin-bottom-large" bg_url="http://cdn2-adventure-tours.themedelight.com/wp-content/uploads/2015/09/most-popular-bg.jpg"]
	[/vc_column]
[/vc_row]
[vc_row]
	[vc_column]
		[tours_grid title_underline="on" description_words_limit="20" number="4" price_style="default" show_categories="on" btn_more_text="View more" order="DESC" orderby="date" title="DEALS AND DISCOUNTS" sub_title="Sagittis vulputate magna sagittis sagittis erat feugiat nullam cubilia amet dignissim Euismod." btn_more_link="#" css_class="margin-bottom-large"]
	[/vc_column]
[/vc_row]
[vc_row]
	[vc_column]
		[tour_category_images title_underline="on" ignore_empty="on" slides_number="4" order="ASC" orderby="name" title="DESTINATION" sub_title="Find a Tour by" css_class="section-white"]
	[/vc_column]
[/vc_row]
[vc_row]
	[vc_column]
		[tour_category_icons title_underline="on" ignore_empty="on" slides_number="5" order="ASC" orderby="name" title="TOUR TYPE" sub_title="Find a Tour by" bg_url="http://cdn2-adventure-tours.themedelight.com/wp-content/uploads/2015/09/mountain-690104_1920-optimized.jpg"]
	[/vc_column]
[/vc_row]
[vc_row el_class="section-white padding-top-large padding-bottom"]
	[vc_column offset="vc_col-md-6"]
		[latest_posts title="Latest Posts" title_underline="on" number="1" read_more_text="Read more" words_limit="25" ignore_sticky_posts="on" translate="on" order="DESC" orderby="date"]
	[/vc_column]
	[vc_column offset="vc_col-md-6"]
		[tour_reviews title_underline="on" number="2" order="DESC" orderby="comment_date_gmt" title="TOUR REVIEWS"]
	[/vc_column]
[/vc_row]
[vc_row full_width="stretch_row"]
	[vc_column]
		[mailchimp_form button_text="Submit" width_mode="full-width" bg_repeat="repeat" form_id="1" title="JOIN THE NEWSLETTER" css_class="stick-to-bottom" bg_url="http://cdn2-adventure-tours.themedelight.com/wp-content/uploads/2015/09/mountain-river-optimized2.jpg"]To receive our best monthly deals[/mailchimp_form]
	[/vc_column]
[/vc_row]